CREATE OR REPLACE TABLE JAGUAR_ECOMERSE_DB.NESHTO.orders_formatted (
    Order_ID INTEGER,
    Customer_ID VARCHAR(10),
    Customer_Name VARCHAR(100),
    Order_Date DATE,
    Product VARCHAR(100),
    Quantity INTEGER,
    Price INTEGER,
    Discount DECIMAL(5,2),
    Total_Amount DECIMAL(15,2),
    Payment_Method VARCHAR(50),
    Shipping_Address VARCHAR(255),
    Status VARCHAR(20)
);

USE DATABASE  _JAGUAR_GLOBAL_DB;
LIST @ECCOMERCE_SOURCE;

CREATE OR REPLACE FILE FORMAT my_csv_format
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null', '')
  FIELD_OPTIONALLY_ENCLOSED_BY = '"';
CREATE  FILE FORMAT my_csv_format
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  NULL_IF = ('NULL', 'null', '')
  FIELD_OPTIONALLY_ENCLOSED_BY = '"';

use warehouse ANIMAL_TASK_WH;

CREATE TABLE JAGUAR_ECOMERSE_DB.NESHTO.orders_raw (
    Order_ID VARCHAR,
    Customer_ID VARCHAR,
    Customer_Name VARCHAR,
    Order_Date VARCHAR,
    Product VARCHAR,
    Quantity VARCHAR,
    Price VARCHAR,
    Discount VARCHAR,
    Total_Amount VARCHAR,
    Payment_Method VARCHAR,
    Shipping_Address VARCHAR,
    Status VARCHAR
);


COPY INTO JAGUAR_ECOMERSE_DB.NESHTO.ORDERS_RAW
FROM @_JAGUAR_GLOBAL_DB.INTERNAL_STAGE.ECCOMERCE_SOURCE/ecommerce_orders.csv
FILE_FORMAT = (FORMAT_NAME = 'MY_CSV_FORMAT');
select * from JAGUAR_ECOMERSE_DB.NESHTO.ORDERS_RAW;




CREATE OR REPLACE  TABLE JAGUAR_ECOMERSE_DB.NESHTO.td_invalid_date_format  AS
    SELECT *
    FROM JAGUAR_ECOMERSE_DB.NESHTO.ORDERS_RAW
    WHERE TRY_TO_DATE(ORDER_DATE, 'yyyy-mm-dd') IS NULL;

SELECT * FROM JAGUAR_ECOMERSE_DB.NESHTO.td_invalid_date_format;
   Delete
    FROM JAGUAR_ECOMERSE_DB.NESHTO.ORDERS_RAW
    WHERE TRY_TO_DATE(ORDER_DATE, 'yyyy-mm-dd') IS NULL;





INSERT INTO JAGUAR_ECOMERSE_DB.NESHTO.ORDERS_FORMATTED
SELECT ORDER_ID,
       CUSTOMER_ID,
       CUSTOMER_NAME,
       ORDER_DATE,
       PRODUCT,
       QUANTITY,
       PRICE,
       DISCOUNT,
       TOTAL_AMOUNT,
       PAYMENT_METHOD,
       SHIPPING_ADDRESS,
       STATUS
FROM JAGUAR_ECOMERSE_DB.NESHTO.ORDERS_RAW
QUALIFY  ROW_NUMBER() OVER (
    PARTITION BY  ORDER_ID
    ORDER BY ORDER_ID
    ) = 1;

SELECT  * FROM JAGUAR_ECOMERSE_DB.NESHTO.ORDERS_FORMATTED ORDER BY ORDER_ID;





CREATE OR REPLACE TABLE JAGUAR_ECOMERSE_DB.NESHTO.td_for_review AS
    SELECT *
    FROM JAGUAR_ECOMERSE_DB.NESHTO.ORDERS_FORMATTED
    WHERE STATUS = 'Delivered' AND SHIPPING_ADDRESS IS NULL;

SELECT * FROM JAGUAR_ECOMERSE_DB.NESHTO.td_for_review;

DELETE
FROM JAGUAR_ECOMERSE_DB.NESHTO.ORDERS_FORMATTED
    WHERE STATUS = 'Delivered' AND SHIPPING_ADDRESS IS NULL;




CREATE OR REPLACE TABLE JAGUAR_ECOMERSE_DB.NESHTO.td_suspicious_records AS
    SELECT *
    FROM JAGUAR_ECOMERSE_DB.NESHTO.ORDERS_FORMATTED
    WHERE CUSTOMER_ID IS NULL OR CUSTOMER_NAME IS NULL;

SELECT * FROM JAGUAR_ECOMERSE_DB.NESHTO.td_suspicious_records;

DELETE
FROM JAGUAR_ECOMERSE_DB.NESHTO.ORDERS_FORMATTED
   WHERE CUSTOMER_ID IS NULL OR CUSTOMER_NAME IS NULL;





CREATE OR REPLACE TABLE JAGUAR_ECOMERSE_DB.NESHTO.td_invalid_price_quantity AS
    SELECT *
    FROM JAGUAR_ECOMERSE_DB.NESHTO.ORDERS_FORMATTED
    WHERE QUANTITY < 0 OR PRICE < 0 OR TOTAL_AMOUNT < 0;

SELECT * FROM JAGUAR_ECOMERSE_DB.NESHTO.td_invalid_price_quantity;


DELETE FROM JAGUAR_ECOMERSE_DB.NESHTO.ORDERS_FORMATTED
WHERE QUANTITY < 0 OR PRICE < 0;



UPDATE JAGUAR_ECOMERSE_DB.NESHTO.ORDERS_FORMATTED
SET PAYMENT_METHOD = 'Unknown'
WHERE PAYMENT_METHOD IS NULL;


UPDATE JAGUAR_ECOMERSE_DB.NESHTO.ORDERS_FORMATTED
SET DISCOUNT =
CASE
    WHEN DISCOUNT > 0.50 THEN 0.50
    WHEN DISCOUNT < 0 THEN 0
    ELSE DISCOUNT
END
WHERE DISCOUNT > 0.50 OR DISCOUNT < 0;


UPDATE JAGUAR_ECOMERSE_DB.NESHTO.ORDERS_FORMATTED
SET TOTAL_AMOUNT = PRICE * QUANTITY * (1 - DISCOUNT)
WHERE TOTAL_AMOUNT = PRICE * QUANTITY * (1 - DISCOUNT);

UPDATE JAGUAR_ECOMERSE_DB.NESHTO.ORDERS_FORMATTED
SET  STATUS = 'Pending'
WHERE  SHIPPING_ADDRESS IS NULL;

SELECT  * FROM JAGUAR_ECOMERSE_DB.NESHTO.ORDERS_FORMATTED;


CREATE SCHEMA  JAGUAR_ECOMERSE_DB.FINAL;

CREATE OR REPLACE TABLE JAGUAR_ECOMERSE_DB.FINAL.td_clean_records (
    Order_ID INTEGER,
    Customer_ID VARCHAR(10),
    Customer_Name VARCHAR(100),
    Order_Date DATE,
    Product VARCHAR(100),
    Quantity INTEGER,
    Price INTEGER,
    Discount DECIMAL(5,2),
    Total_Amount DECIMAL(15,2),
    Payment_Method VARCHAR(50),
    Shipping_Address VARCHAR(255),
    Status VARCHAR(20)
);


INSERT INTO  JAGUAR_ECOMERSE_DB.FINAL.td_clean_records
SELECT ORDER_ID,
       CUSTOMER_ID,
       CUSTOMER_NAME,
       ORDER_DATE,
       PRODUCT,
       QUANTITY,
       PRICE,
       DISCOUNT,
       TOTAL_AMOUNT,
       PAYMENT_METHOD,
       SHIPPING_ADDRESS,
       STATUS
FROM NESHTO.ORDERS_FORMATTED;